feat: 新增FastImage.preload支持
react-native-oh-library/react-native-fast-image pull request #39
Opened 2024-07-27 08:52 UTC by cmdssd

# Summary

请解释此次更改的 **动机**，以下是一些帮助您的要点：

- 新增FastImage.preload支持
closed #38 

## Checklist

- [ ] 已经在真机设备或模拟器上测试通过
- [ ] 已经与 Android 或 iOS 平台做过效果/功能对比
- [ ] 已经添加了对应 API 的测试用例（如需要）
- [ ] 已经更新了文档（如需要）
- [ ] 更新了 JS/TS 代码 (如有)

2024-07-29 09:04 UTC, Louis-C7 requested changes

2024-07-29 09:04 UTC, Louis-C7 commented on harmony/fast_image/src/main/ets/RNCFastImageViewTurboModule.ts
>    }
挪到cpp实现的话，这里可以删掉

2024-07-29 09:04 UTC, Louis-C7 commented on harmony/fast_image/src/main/cpp/RNCFastImageViewTurboModule.cpp
> +    void RNCFastImageViewTurboModule::preload(facebook::jsi::Runtime &rt,const facebook::jsi::Value *args, size_t count)
格式化一下

2024-07-29 09:04 UTC, Louis-C7 commented on harmony/fast_image/src/main/cpp/RNCFastImageViewTurboModule.cpp
> +    if(count == 1){
这个判断用来干嘛？

2024-07-29 09:04 UTC, Louis-C7 commented on harmony/fast_image/src/main/ets/RNCFastImageViewTurboModule.ts
> +      resolve(null)
有没有可能失败？

2024-07-29 09:04 UTC, Louis-C7 commented on harmony/fast_image/src/main/ets/RNCFastImageViewTurboModule.ts
> +      resolve(null)
同上

2024-07-29 09:08 UTC, Louis-C7 requested changes

2024-07-29 09:08 UTC, Louis-C7 commented on harmony/fast_image/src/main/cpp/FastImageViewComponentInstance.cpp
> +
出现过已知问题，FindLocalCacheByUri返回来uri，uri为有效的缓存路径。但传递给Image之后，Image说这个缓存不存在。需要看下不为空的情况下，如何判断这个uri对应的缓存文件还存在

2024-07-29 09:55 UTC, dream-approaching commented on harmony/fast_image/src/main/ets/FastRemoteImageLoader/RemoteImageLoader.ts
> +    if (this.memoryCache.has(uri)) {
这个if语句是不是和50行重复了

2024-07-29 09:55 UTC, dream-approaching commented on harmony/fast_image/src/main/ets/FastRemoteImageLoader/RemoteImageDiskCache.ts
> +    const reg = /[^a-zA-Z0-9 -]/g;
正则初始化比较耗性能 对于固定的可以提到外面，只需要初始化一次

2024-07-29 09:55 UTC, dream-approaching commented on harmony/fast_image/src/main/ets/FastImagePackage.ts
> +import {
type表示类型 去掉的原因是？  如果去掉的话，建议和上面那行合并一下

2024-07-29 09:55 UTC, dream-approaching commented on harmony/fast_image/src/main/ets/FastRemoteImageLoader/RemoteImageCache.ts
> +  keys():IterableIterator<string>{
冒号后面空格 跟其他的保持一致

2024-07-30 03:43 UTC, cmdssd commented on harmony/fast_image/src/main/ets/RNCFastImageViewTurboModule.ts
>    }
已修改

2024-07-30 03:43 UTC, cmdssd commented on harmony/fast_image/src/main/cpp/RNCFastImageViewTurboModule.cpp
> +    void RNCFastImageViewTurboModule::preload(facebook::jsi::Runtime &rt,const facebook::jsi::Value *args, size_t count)
已修改

2024-07-30 03:44 UTC, cmdssd commented on harmony/fast_image/src/main/cpp/RNCFastImageViewTurboModule.cpp
> +    if(count == 1){
已修改

2024-07-30 03:44 UTC, cmdssd commented on harmony/fast_image/src/main/ets/RNCFastImageViewTurboModule.ts
> +      resolve(null)
已修改

2024-07-30 03:44 UTC, cmdssd commented on harmony/fast_image/src/main/ets/RNCFastImageViewTurboModule.ts
> +      resolve(null)
已修改

2024-07-30 03:44 UTC, cmdssd commented on harmony/fast_image/src/main/cpp/FastImageViewComponentInstance.cpp
> +
已修改,做了个文件存在验证

2024-07-30 03:45 UTC, cmdssd commented on harmony/fast_image/src/main/ets/FastRemoteImageLoader/RemoteImageDiskCache.ts
> +    const reg = /[^a-zA-Z0-9 -]/g;
已修改

2024-07-30 03:45 UTC, cmdssd commented on harmony/fast_image/src/main/ets/FastImagePackage.ts
> +import {
已修改

2024-07-30 03:45 UTC, cmdssd commented on harmony/fast_image/src/main/ets/FastRemoteImageLoader/RemoteImageCache.ts
> +  keys():IterableIterator<string>{
已修改

2024-08-02 01:58 UTC, Louis-C7 requested changes

2024-08-02 01:58 UTC, Louis-C7 commented on harmony/fast_image/src/main/cpp/FastImageViewComponentInstance.cpp
> +        if(ret == 0){
用枚举值

2024-08-02 01:58 UTC, Louis-C7 commented on harmony/fast_image/src/main/ets/FastImageLoaderTurboModule.ts
> +    console.log('FastImageLoaderTurboModule sss')
删掉

2024-08-02 03:20 UTC, closed without merging